language: ruby
bundler_args: --without=development
before_install: bundle exec rake test:prepare:xvfb
  - 
before_script: bundle exec rake db
script: bundle exec rspec --format=documentation
after_success: bundle exec rake deploy
